---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    kafka: consumer
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      kafka: consumer
  template:
    metadata:
      name: kafka-consumer
      labels:
        kafka: consumer
    spec:
      hostNetwork: true
      containers:
        - name: kafka-consumer
          image: jjino/azure-hdinsights-kafka-consumer:v1
          env:
            - name: KAFKA_HOST
              value: "10.42.60.7:9092,10.42.60.6:9092,10.42.60.5:9092"
            - name: KAFKA_TOPIC
              value: "test"
